[package]
name = "bookshelf-api"
version = "1.0.0"
edition = "2021"
authors = ["Aksiome"]
description = "REST API for the Bookshelf project"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0.95"
axum = "0.8.1"
cached = { version = "0.54.0", features = ["async"] }
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }
zip = "2.2.2"

[profile.release]
strip = true
lto = true
opt-level = "s"
codegen-units = 1
